### ISSUE TITLE
wholeBodyImpedance need to be ported to the WBT 2.0 

### ISSUE THREAD

**Issue by traversaro** [robotology-playground/WBI-Toolbox-controllers#16]
@gabrielenava @DanielePucci

**Comment by DanielePucci** [comment]
@gabrielenava, may you please do this?

**Comment by gabrielenava** [comment]
I'll start working on it today

**Comment by gabrielenava** [comment]
done at https://github.com/robotology-playground/WBI-Toolbox-controllers/commit/d33033f15f791aaf4273b6188862c1f4bf56160d
