### ISSUE TITLE
Cleanup of directory names

### ISSUE THREAD

**Issue by traversaro** [robotology-playground/WBI-Toolbox-controllers#17]
The mantained version of the controllers that use WB-Toolbox 2.0 should have obvious names, not the current `torqueBalancing_WBT`. Otherwise it is certaint that almost all user would open the old one by mistake. 

I propose to move the "old" controllers in a legacy subfolder:

```
controllers/torqueBalancing --> controllers/legacy/torqueBalancing
controllers/wholeBodyImpedance --> controllers/legacy/wholeBodyImpedance
```

Then we can rename the current versions to have intuitive names:

```
controllers/torqueBalancingWBT --> controllers/torqueBalancing
```

cc @DanielePucci @gabrielenava 
ref https://github.com/robotology/WB-Toolbox/issues/10

**Comment by DanielePucci** [comment]
:+1:

**Comment by traversaro** [comment]
I think @gabrielenava can handle this (you just need to use `git mv`, I can explain how to do it properly).

**Comment by traversaro** [comment]
Done in https://github.com/robotology-playground/WBI-Toolbox-controllers/commit/54601b9e3aaa11868bdd9dffe834e44ecd563a72 .
