### ISSUE TITLE
[BUG] README with broken links 

### ISSUE THREAD

**Issue by iron76** [robotology-playground/WBI-Toolbox-controllers#21]
The README of the project has a broken link in the torqueBalancingJc README.

**Comment by DanielePucci** [comment]
@gabrielenava may you fix these links?

**Comment by gabrielenava** [comment]
Done at https://github.com/robotology-playground/WBI-Toolbox-controllers/commit/b985d6da836ed37aed34ad179c16c20c64dc89ad . Actually, the current version of the joint space controller is under pull request, so the link is now pointing the torqueBalancingJointControl/README.md in the ModifJointControl branch. It will be updated again after merging the branch into master

**Comment by iron76** [comment]
There is still some issue in the link torqueBalancingJc README.

**Comment by gabrielenava** [comment]
this commit https://github.com/robotology-playground/WBI-Toolbox-controllers/commit/2f2597da70529e081920e7133971889653086bad on the master branch and this one https://github.com/robotology-playground/WBI-Toolbox-controllers/commit/55aa79e9f45d1cd1b374069aa13d8fdc0b18f42a  on the ModifJointControl branch should definitely fix the bug

**Comment by gabrielenava** [comment]
Closing this issue
