### ISSUE TITLE
Gravity compensation not working properly on torso

### ISSUE THREAD

**Issue by DanielePucci** [robotology-playground/WBI-Toolbox-controllers#22]
We tried the wholeBodyImpedance controller by zeroing the gains. We were expecting that the gravity compensation would more or less do a good job, being the model reliable right now. In fact,, this was the case for the legs and the arms, but the torso was still falling quite abruptly. @traversaro @francesco-romano @nunoguedelha

**Comment by traversaro** [comment]
Related issue : https://github.com/robotology-playground/insitu-ft-analysis/issues/5 .

**Comment by DanielePucci** [comment]
Fixed after https://github.com/robotology/icub-main/commit/4a8c4f2e34980153d98b2d06a31ada8d33736e01
