### ISSUE TITLE
MATLAB setenv/getenv does not play nice with NetworkBase::getEnvironment 	

### ISSUE THREAD

**Issue by traversaro** [robotology-playground/WBI-Toolbox-controllers#27]
http://www.yarp.it/classyarp_1_1os_1_1NetworkBase.html#a283af07d20c62b6eb9826f9bda68c3f2

**Comment by DanielePucci** [comment]
Hi @traversaro , what do you mean by "does not play nice"?

**Comment by traversaro** [comment]
Enviromental variables set by matlab (as in https://github.com/robotology-playground/WBI-Toolbox-controllers/blob/d7a21f545d1ba75ba68679ab37d0c23e9225da56/controllers/wholeBodyImpedance/init_impedanceControl.m#L30) are not seen by the underlying C++ code in the `WB-Toolbox`. Still needs to be investigated.

**Comment by DanielePucci** [comment]
Got it. Thanks.

**Comment by francesco-romano** [comment]
It seems to happen only in Windows

**Comment by gabrielenava** [comment]
`setenv` and `getenv` are no more used in [whole-body-controllers](https://github.com/robotology/whole-body-controllers). Closing.
