### ISSUE TITLE
MATLAB setenv/getenv does not play nice with YARP's NetworkBase::getEnvironment 	

### ISSUE THREAD

**Issue by traversaro** [robotology-playground/WBI-Toolbox-controllers#28]
[`NetworkBase::getEnvironment`](http://www.yarp.it/classyarp_1_1os_1_1NetworkBase.html#a283af07d20c62b6eb9826f9bda68c3f2)

**Comment by gabrielenava** [comment]
Closing as a duplicate of https://github.com/robotology-playground/WBI-Toolbox-controllers/issues/27
