### ISSUE TITLE
Obtain geometry of the contact/support surface from the iCub skin

### ISSUE THREAD

**Issue by traversaro** [robotology-playground/WBI-Toolbox-controllers#36]
Until now, the geometry of the contact surface (typically the sole of the feet) has been hardcoded in the controllers using the `phys.footSize` and `gain.footSize` parameters [1], that express the support area as a rectangle in the `l_sole` or `r_sole` frames. This information is important 
because it imposes the set of physical contact force/torques that the robot can exert on the contact surface without slipping or tipping. 

For the CoDyCo Y4 Demo, we needed to balance the robot with the `l_upper_leg`/`r_upper_leg` links that are in contact with a side of the structural beam profiles, such as this one:
![02_profilato_superleggero_b03-1_30x30__applicazione_big](https://cloud.githubusercontent.com/assets/1857049/21431385/4bfab37a-c867-11e6-8a87-f7e11467ab7f.jpeg)

 As the beam profile is in contact only with part of the cover of the `*_upper_leg` link, we need to estimated online with part of the leg is actually in contact with the beam profile. This can be done with the iCub skin, but need some custom software. 

[1] See for example : https://github.com/robotology-playground/WBI-Toolbox-controllers/blob/e88439c24bcaecd3f2bfad4629cf359073a154ea/controllers/torqueBalancing/app/robots/iCubGenova02/gains.m#L122 .

**Comment by iron76** [comment]
👍 When you write "with part of the leg is actually in contact" you mean "which area of the leg is actually in contact"?

**Comment by gabrielenava** [comment]
After discussing with @Yeshasvitvs, we decided to close this issue as achieving a precise contact area size is not critical for the controller and the empirical size estimated by hand-measurements is enough for  now. Closing
