### ISSUE TITLE
[torqueBalancing] Instabilities when using velocities provided by Gazebo

### ISSUE THREAD

**Issue by DanielePucci** [robotology-playground/WBI-Toolbox-controllers#4]
When using the option

```
readSpeedAccFromControlBoard
```

in the configuration file yarpWholeBodyInterface.ini, which enables velocity readings from Gazebo and skip the estimation by adaptive filters, the controller is not stable.

**Comment by DanielePucci** [comment]
As for a unit test, I'm using the controller positionControl, which gives sinusoidal reference joint trajectories to all 23 DOFs. The robot is fixed, and I run the simulations twice, without and with the flag

```
readSpeedAccFromControlBoard
```

in the configuration file yarpWholeBodyInterface.ini. 

The velocities estimated by the adaptive filters are: 

![qd_from_filters](https://cloud.githubusercontent.com/assets/5045846/6993176/9fcba604-daec-11e4-9508-d74bf940fb34.png)

while the velocities provided by Gazebo are

![qd_from_gazebo](https://cloud.githubusercontent.com/assets/5045846/6993184/d8ee0670-daec-11e4-8f8b-195d2d70757a.png)

Any clue on these sharp variations? @traversaro @francesco-romano

**Comment by traversaro** [comment]
Mhh I guess it could be related to ODE errors, perhaps fine tuning some parameters could mitigate this problem..

**Comment by gabrielenava** [comment]
Outdated issue. Closing.
