### ISSUE TITLE
Toolbox for exporting Simulink model in previous version automatically

### ISSUE THREAD

**Issue by gabrielenava** [robotology-playground/WBI-Toolbox-controllers#42]
Given the number of different Simulink versions we are using, this can be useful to ensure all users can access the most updated version of the code.

**Comment by francesco-romano** [comment]
You can try if you are able to make [this](https://github.com/robotology/WB-Toolbox/blob/master/toolbox/export_library.m) work

See https://github.com/robotology/WB-Toolbox/issues/1

**Comment by gabrielenava** [comment]
first version of this toolbox presented in branch `icub_standUp` and working fine. I will soon test it on master

**Comment by traversaro** [comment]
@gabrielenava What is the status of this issue? The tool is working?

**Comment by gabrielenava** [comment]
The function for exporting the model has been added to master since a while (https://github.com/robotology-playground/WBI-Toolbox-controllers/blob/master/controllers/torqueBalancing/exportMdl.m).  I recently used it in iCubStandup and walkman@rbc branches, and I remember I tested it before adding it to master. However, I cannot verify right now it the script is still working properly.

**Comment by francesco-romano** [comment]
Yes, the script works like a charm for model files. 
For some reasons I was never able to make it work for libraries
