### ISSUE TITLE
 icubGazeboSim and iCubGenova02 models have frames oriented differenlty

### ISSUE THREAD

**Issue by gabrielenava** [robotology-playground/WBI-Toolbox-controllers#46]
There is a mismatch between the iCub model used for simulations and the one of iCubGenova02. The frames `l_upper_leg contact` and `r_upper_leg_contact` are oriented differently, as it is possible to see in the following images:

![icubframes](https://cloud.githubusercontent.com/assets/12396934/24405291/a2c1517a-13c4-11e7-81fc-91cbeaa069b2.jpg)
![icubsimframes](https://cloud.githubusercontent.com/assets/12396934/24405292/a3e7a8ba-13c4-11e7-9c4d-6764408d5235.jpg)

these frames are currently used only for `iCub stand up` simulation. Since `l_upper_leg_contact` at the initial time is taken as inertial reference frame, this mismatch causes the CoM references to have different signs in simulations and on the robot. The "correct" orientation is the one of icubSim, because it is the same of `l_sole` (while sitting) and therefore in this way all demos (Yoga, Coordinator, Standup) have the same references signs. Since I am for now the only user of iCub stand up demo on iCubGenova02, I will take care of regenerating the frames from CAD.

**Comment by gabrielenava** [comment]
Corrected for the 4th year CoDycCo demo. Closing this issue

**Comment by traversaro** [comment]
@gabrielenava Please note that the related issue https://github.com/robotology-playground/icub-model-generator/issues/42 is still open and should be address to make sure that all the CoDyCo partners can correctly run the CoDyCo Y4 Demo.

**Comment by gabrielenava** [comment]
I'm aware of this issue, and I will start working on this more or less now (still 1 issue to fix in WBIToolbox-controllers before changing github repo)

**Comment by traversaro** [comment]
:+1:
