### ISSUE TITLE
question about the floating base calculations

### ISSUE THREAD

**Issue by azadm** [robotology-playground/WBI-Toolbox-controllers#5]
I am wondering what the first 16 elements of `q` of the floating base are and why they are set to `0` for calculation of the equilibrium point?
Thanks in advance

**Comment by DanielePucci** [comment]
Hi Morteza,
the point is that the pose of the base is computed internally, and the first 16 elements of the vector are ignored. This is clearly a temporary solution. If you are interested in the floating base pose, however, you should fine the associated block.

Best
