### ISSUE TITLE
Update documentation of the repo

### ISSUE THREAD

**Issue by gabrielenava** [robotology-playground/WBI-Toolbox-controllers#57]
It seems to me the README.md files in every controller folder are outdated. An example:

in this [README](https://github.com/robotology-playground/WBI-Toolbox-controllers/blob/master/controllers/torqueBalancing/README.md), it is stated that one must run `wholeBodyDynamicsTree` in simulation, which has been substituted by `wholeBodyDynamics`. Also `twoFeetStandingIdleAndCalib` is not used anymore in simulation, and it is substituted by sending `resetOffset all` command to wholeBodyDynamics.

**Comment by gabrielenava** [comment]
As noted by [@yeshasvitvs](https://github.com/Yeshasvitvs), there are also comments inside matlab functions that are not updated (e.g. wrong files names, and so on). Therefore we're going to fix these typos and proceed with the cleanup.

**Comment by yeshasvitirupachuri** [comment]
@gabrielenava I cleaned up the typos and opened a [PR](https://github.com/robotology-playground/WBI-Toolbox-controllers/pull/60). Please review it.

**Comment by gabrielenava** [comment]
done with https://github.com/robotology-playground/WBI-Toolbox-controllers/commit/96fd372de2257bf603ea2a4f7dfef6581b631d85
