### ISSUE TITLE
Binary files committed to branch **newControlArchitectureCleanedUp**

### ISSUE THREAD

**Issue by DanielePucci** [robotology-playground/WBI-Toolbox-controllers#59]
Hi @pi-q,
I noticed that you pushed binary files to this repo, e.g. [this](https://github.com/robotology-playground/WBI-Toolbox-controllers/tree/newControlArchitectureCleanedUp/controllers/torqueWalking/slprj).

This is a really bad practice since every pull now takes a long time.

Please pay extreme attention to this, and please fix the mess as soon as possible.

**Comment by gabrielenava** [comment]
binary files have been removed from the repo (see https://github.com/robotology-playground/WBI-Toolbox-controllers/commit/919bf06437a39e6151c6ba70ebb4542fd4416879). closing
