### ISSUE TITLE
Move completeForceControlScripts in legacy

### ISSUE THREAD

**Issue by gabrielenava** [robotology-playground/WBI-Toolbox-controllers#61]
I was wondering what is [completeForceControlScripts](https://github.com/robotology-playground/WBI-Toolbox-controllers/tree/master/controllers/completeForceControlScripts) folder used for. It only contains two matlab scripts (last update 2015). Can I move it inside [legacy](https://github.com/robotology-playground/WBI-Toolbox-controllers/tree/master/controllers/legacy) folder?

cc: @DanielePucci

**Comment by DanielePucci** [comment]
yes: it implements some of the algorithms developed in Del Prete thesis
