### ISSUE TITLE
Should we remove old configuration files?

### ISSUE THREAD

**Issue by gabrielenava** [robotology-playground/WBI-Toolbox-controllers#62]
Inside the [app/robots](https://github.com/robotology-playground/WBI-Toolbox-controllers/tree/master/controllers/torqueBalancing/app/robots) folder of `torqueBalancing` and `wholeBodyImpedance` controllers there are configuration files for different robots. I think some of them are quite old and probably they are not even usable anymore. In particular:

#### torqueBalanging

- iCubDarmstadt01
- iCubGenova01
- iCubGenova03
- iCubGenova05
- iCubParis01
- iCubParis01

#### wholeBodyImpedance

- iCubDarmstadt01

should we remove them? also considering that even if deleted we can recover them if necessary looking at github history.

cc @DanielePucci

**Comment by DanielePucci** [comment]
Why can't we keep them?

**Comment by gabrielenava** [comment]
I opened them and they probably cannot work anymore because of missing variables, therefore I think that if we're going to work on one of these robots best solution will be to copy-paste configuration files from another one (probably iCubGenova04). But I agree that removing those files may be considered "premature optimization" [cit.]

**Comment by traversaro** [comment]
I agree to remove those files, also to clarify which platform we are supporting and which platform we are not supporting. git remembers, so even deleting it does not mean that we cannot recover them in the future.

**Comment by gabrielenava** [comment]
ok then! I'm going to remove these files.

**Comment by gabrielenava** [comment]
done with https://github.com/robotology-playground/WBI-Toolbox-controllers/commit/96fd372de2257bf603ea2a4f7dfef6581b631d85
