### ISSUE TITLE
Weird behavior of gravity compensation on icubGazeboSim

### ISSUE THREAD

**Issue by gabrielenava** [robotology-playground/WBI-Toolbox-controllers#66]
I did a simple modification of [wholeBodyImpedance](https://github.com/robotology-playground/WBI-Toolbox-controllers/tree/master/controllers/wholeBodyImpedance):

![screenshot from 2017-10-27 12-40-59](https://user-images.githubusercontent.com/12396934/32100458-1ccce5c8-bb14-11e7-80cc-58fdfb630cef.png)

I took the gravity compensation part. I removed the feedback + feedforward part. I substituted it with a block that can do a sweep in frequency on a sine function. **I set the AMPLITUDE of the sine to zero** to verify the effectiveness of gravity compensation with icubGazeboSim. This is the result (after 30 [s] of simulation):

![screenshot from 2017-10-27 12-44-15](https://user-images.githubusercontent.com/12396934/32100577-8ede94ea-bb14-11e7-8867-1c9143e2dca4.png)

It is possible to reproduce the same behavior using [wholeBodyImpedance](https://github.com/robotology-playground/WBI-Toolbox-controllers/tree/master/controllers/wholeBodyImpedance). I did the following modification:

![screenshot from 2017-10-27 12-37-37](https://user-images.githubusercontent.com/12396934/32100608-b3bab866-bb14-11e7-8f30-c2df4f196b81.png)

it is the classical wholeBodyImedance controller but **I added three GAIN blocks in which I set the gain to zero in order to remove the feedforward/feedback part**. This is the result after 30[s]:

![screenshot from 2017-10-27 12-48-12](https://user-images.githubusercontent.com/12396934/32100705-1dafcc16-bb15-11e7-9d24-d08375e702b2.png)

and these are the gravity torques:

![screenshot from 2017-10-27 12-49-01](https://user-images.githubusercontent.com/12396934/32100730-38e89d0a-bb15-11e7-8e07-f1d008e11acc.png)

I know this may be due to integration errors in Gazebo, still these results are really bad to me. It seems to me strange that gravity compensation is so bad. I cannot understand why. Furthermore, this is what happens if I try to control only 1 joint (in the picture: torso pitch, joint torque):

![screenshot from 2017-10-27 12-53-30](https://user-images.githubusercontent.com/12396934/32100877-d9374b8a-bb15-11e7-818a-a89819ed3387.png)

I cannot understand this at all. Why I can't control only the torso pitch in torque mode? 

This is what is inside the gravity compensation block:

![screenshot from 2017-10-27 12-59-09](https://user-images.githubusercontent.com/12396934/32101023-a4a35642-bb16-11e7-94bd-a0005a65819e.png)

**Comment by traversaro** [comment]
> I cannot understand this at all. Why I can't control only the torso pitch in torque mode? 

Remember that if you control only one joint, the model will assume that all other joints are set to 0, so the gravity compensation will probably totally wrong.

**Comment by traversaro** [comment]
To debug the gravity compensation, I suggest to start by comparing the gravity compensation torques and the torque provided by the PID low level control, to see if they are ~consistent.

**Comment by traversaro** [comment]
Anyhow, consider that the `icubGazeboSim` model available in icub-gazebo has been manually modified a lot of time (when the eyes and hands have been added, etc etc). I would suggest to do this tests on the new iCubGazeboV2_5 introduced in https://github.com/robotology-playground/icub-model-generator/pull/71 .

**Comment by gabrielenava** [comment]
>> I cannot understand this at all. Why I can't control only the torso pitch in torque mode? 
>
>Remember that if you control only one joint, the model will assume that all other joints are set to 0, so the gravity compensation will probably totally wrong. 

Ok thanks, this explains why it failed when I tried it only with torso pitch.

I actually tried the same test using Walkman model, and I got the same results. Maybe it is due to numerical integration errors?

**Comment by traversaro** [comment]
Mhh I think we should chat about this on skype/appear.

**Comment by gabrielenava** [comment]
I tested the gravity compensation only on the legs. I also compared the desired torques with the measured (are these torques the one provided by the PID low level control also in simulation? does it make sense to do this comparison in simulation?). This is the torque error:

![screenshot from 2017-10-27 15-06-57](https://user-images.githubusercontent.com/12396934/32105487-ee7d35e6-bb28-11e7-9aae-55cc7a11bc59.png)

it is almost always zero, but there's a strange peak and I don't know why, but I don't think is related to the gravity compensation issue. Indeed, the gravity compensation is way better on the legs (the derive is much slower in 30 [s]). See the picture below.

![screenshot from 2017-10-27 15-07-22](https://user-images.githubusercontent.com/12396934/32105606-5e2decaa-bb29-11e7-9361-20773990aafc.png)

So I really think we're debugging numerical integration issue.

**Comment by traversaro** [comment]
>  numerical integration issue

Nitpick; in general consider that there are several points in which the classical multibody dynamic is "approximated" in the ODE physics engine (see http://robotics.cs.tamu.edu/dshell/papers/simpar2010ode.pdf), so it can be also a numerical simulation issue that **is not** related to integration algorithms.

**Comment by gabrielenava** [comment]
I tested the gravity compensator on real robot, it was working fine even without feedback terms. We can close this issue.
