### ISSUE TITLE
Move this repo to Robotology Legacy?

### ISSUE THREAD

**Issue by gabrielenava** [robotology-playground/WBI-Toolbox-controllers#68]
After properly document it, if everybody agrees.

**Comment by gabrielenava** [comment]
@traversaro I think this repo is ready to be moved in `robotology-legacy`, what do you think about it?

**Comment by traversaro** [comment]
I agree.

**Comment by traversaro** [comment]
Done. Feel free to close this issue, and then I will archive the repo.

**Comment by gabrielenava** [comment]
ok! thanks
